services:
  jira:
    container_name: jira-app
    ports:
      - "8080:8080"
    build: .
    image: jira
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: jira-db
    image: postgres:17
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./resources:/opt/jirarush/resources:ro
    depends_on:
      - jira

volumes:
  pgdata:
    driver: local
